# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-12 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('birthday', models.DateTimeField()),
                ('user_level', models.IntegerField()),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='messaging_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_message', to='signin.Users'),
        ),
        migrations.AddField(
            model_name='comments',
            name='commenting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_comment', to='signin.Users'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_comment', to='signin.Messages'),
        ),
    ]
