# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-13 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='desc',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
