# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-13 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_users_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='messaging_user',
        ),
        migrations.AddField(
            model_name='messages',
            name='receive_message_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='receive_users_message', to='signin.Users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='send_message_user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='send_users_message', to='signin.Users'),
            preserve_default=False,
        ),
    ]
